Dear Reviewer, 
<br>Nice to e-meet you. Thank you for reviewing my work. 
<br>I have some questions and marked them with "[QUESTION]".
<br>I would appreciate it if you could answer them as well.
<br>Thank you!
<br>Rena Bracha

<div style="border:solid green 2px; padding: 20px"> <h1 style="color:green; margin-bottom:20px">Reviewer's comment v1</h1>

Hello Rena, my name is Dmitrii. Nice to meet you! 🙌 I'm going to review your project. 
Sure, i will check your questions in the project.

You can find my comments under the heading **«Review»**. I will categorize my comments in green, blue or red boxes like this:

<div class="alert alert-success">
    <b>Success:</b> if everything is done successfully
</div>
<div class="alert alert-warning">
    <b>Remarks:</b> if I can give some recommendations or ways to improve the project
</div>
<div class="alert alert-danger">
    <b>Needs fixing:</b> if the block requires some corrections. Work can't be accepted with the red comments
</div>

Please don't remove my comments :) If you have any questions don't hesitate to respond to my comments in a different section. 
<div class="alert alert-info"> <b>Student comments:</b> For example like this</div>    


<div style="border:solid green 2px; padding: 20px">
<b>Reviewer's comment v1:</b>
    
<b>Overall Feedback</b> 
    
- Overall well done!  I can see that a lot of effort has been made! Your project already looks really good and you accomplished impressive results.
- It is great that you can use different methods for data processing and apply all of that on real data and project tasks, keep it up!
   
- Nevertheless, there is one area for improvement (in red) that will help you to make your project even better: 
    - Extend the overall project conclusions with high level steps you accomplished and recomendations/next steps to the business.
    
I will wait for you to send me a new version of the project with changes :) 
 
And of course, if you have any questions along the way, remember that you can always reach out to your tutor in slack for any clarification. It will be actually faster to get answers from tutor while you are working on the next project and you have questions about the code. 
    
</div>

<div class="alert alert-info"> <b>Student comments:</b> Hi Dmitrii, thank you for taking the time to review my project carefully and kindly providing answers to all my questions. I have revised my work according to your comments. I would appreciate it if you could review just one more time (hopefully this will be the last. :)) Much appreciated! Rena</div>  

<div style="border:solid green 2px; padding: 20px">
<b>Reviewer's comment v2:</b>
    
<b>Overall Feedback</b> 
    
- Thank you for making all corrections in the project :)  Now overall conclusions and project are perfect. 
- No critial issues left, so your project has been accepted! 

Please keep up the great work and good luck on the next project! 
</div>

# Research on car sales ads

Crankshaft List hosts a website where hundreds of sellers advertise vehicles for sale every day free of charge. The company wants to analyse the data collected over the last few years and determine which factors influence the price of a vehicle. 

**Project outline**
* Perform preliminary data exploration to become familiar with the data, wash out illogical values and plan a course of action for more in-depth exploration and data preprocessing, always with the project goal in mind.
* Shape the data into a form that can be processed by taking care of missing values, inconsistencies and duplicates in preparation for analyses. 
* Follow the project instructions and perform calculations as specified at this stage before the analyses. 
* Study the data with the aid of various types of graphs, appropriately selected to visualise the data while augmenting with descriptive statistics. 
* Wrap up with conclusions as to which factors appear to influence the price of a vehicle.


<div class="alert alert-warning">
<b>Reviewer's comment v1:</b>
    
- It would be great to add additional information about project tasks. It gives an overview of what you are going to achieve in this project.
- Also, this introduction potentially can be used as a Readme file in your portfolio on Github. One example of a nice introduction for a data analysis project can be found here: [https://github.com/CICIFLY/Data-Analytics-Projects/blob/master/AB%20Testing%20Result%20Analyze/readme.md](https://github.com/CICIFLY/Data-Analytics-Projects/blob/master/AB%20Testing%20Result%20Analyze/readme.md)
    
</div>

<div class="alert alert-info"> <b>Student comments:</b> Thank you for showing me an example on how to write a project introduction.</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
🙌
</div>

## Open the data file and study the general information. 

**Load the files.**

Load various libraries. 

In [1]:
# Import the pandas library.
import pandas as pd
import numpy as np

# Import sys so no warnings will be issued. 
import sys
if not sys.warnoptions:
    import warnings
    warnings.simplefilter("ignore")
    
# Import Matplotlib
import matplotlib.pyplot as plt

# Import Seaborn
import seaborn as sns

Load the data csv file.

In [2]:
# I worked locally and will have to upload the project to the Platform. So cover both paths. 
# It is a csv file, so the separator is a comma. 
try:
    data = pd.read_csv('vehicles_us.csv', sep = ',')
except:
    data = pd.read_csv('/datasets/vehicles_us.csv', sep = ',')

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
Great that all imports and data load are grouped in different cells before the project. 
</div>

**Explore the data and make some preliminary observations.**

In [3]:
# View some rows to see what the data look like.
data

price  model_year           model  condition  cylinders fuel  odometer  \
0       9400      2011.0          bmw x5       good        6.0  gas  145000.0   
1      25500         NaN      ford f-150       good        6.0  gas   88705.0   
2       5500      2013.0  hyundai sonata   like new        4.0  gas  110000.0   
3       1500      2003.0      ford f-150       fair        8.0  gas       NaN   
4      14900      2017.0    chrysler 200  excellent        4.0  gas   80903.0   
...      ...         ...             ...        ...        ...  ...       ...   
51520   9249      2013.0   nissan maxima   like new        6.0  gas   88136.0   
51521   2700      2002.0     honda civic    salvage        4.0  gas  181500.0   
51522   3950      2009.0  hyundai sonata  excellent        4.0  gas  128000.0   
51523   7455      2013.0  toyota corolla       good        4.0  gas  139573.0   
51524   6300      2014.0   nissan altima       good        4.0  gas       NaN   

      transmission    type paint_color  is_4wd date_posted  days_listed  
0        automatic     SUV         NaN     1.0  2018-06-23           19  
1        automatic  pickup       white     1.0  2018-10-19           50  
2        automatic   sedan         red     NaN  2019-02-07           79  
3        automatic  pickup         NaN     NaN  2019-03-22            9  
4        automatic   sedan       black     NaN  2019-04-02           28  
...            ...     ...         ...     ...         ...          ...  
51520    automatic   sedan       black     NaN  2018-10-03           37  
51521    automatic   sedan       white     NaN  2018-11-14           22  
51522    automatic   sedan        blue     NaN  2018-11-15           32  
51523    automatic   sedan       black     NaN  2018-07-02           71  
51524    automatic   sedan         NaN     NaN  2018-06-05           10  

[51525 rows x 13 columns]

Total number of variables: 13

* price: the price at which the vehicle was sold
* model_year: the year designated to the vehicle model, irrespective of the calendar year in which the vehicle was actually produced 
* model: the name used by the manufacturer to market a range of similar cars
* condition: the condition of the vehicle at the time the ad was placed
* cylinders: the numbers of cylinders to power the engine. The most common are 4, 6 and 8.
* fuel: the type of fuel the vehicle used
* odometer: the distance that had been traveled by the vehicle at the time the ad was placed
* transmission: the method of transferring power from the engine to the wheels
* type: the vehicle type
* paint_color: the colour of the vehicle
* is_4wd: whether the vehicle has a 4x4 system or not
* date_posted: the date on which the ad was placed
* days_listed: the number of days since the ad was placed until it was removed, i.e. the vehicle was not necessarily sold.
 
[Observations]
* missing values (-> Step 2. Data preprocessing)
    <br>o model_year
    <br>o odometer
    <br>o paint_color
    <br>o is_4wd
<br>

* data type conversion (-> Step 2. Data preprocessing)
    <br>o model_year: float -> int [no such thing as "a 2021.5 model" so it makes better sense]
    <br>o cylinders: float -> int [no such thing as "4.6 cylinders" so it makes better sense]
    <br>o is_4wd: float -> boolean [it's either a 4wd or not]
<br>

* variable renaming (-> Step 2. Data preprocessing)
    <br>o odometer: rename to 'mileage' [for ease of understanding]

[Comment]
A side remark - because the csv file is suffixed with "_us", I am guessing that the currency is USD. 

In [4]:
# Get some general info on the data. 
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51525 entries, 0 to 51524
Data columns (total 13 columns):
 #   Column        Non-Null Count  Dtype  
---  ------        --------------  -----  
 0   price         51525 non-null  int64  
 1   model_year    47906 non-null  float64
 2   model         51525 non-null  object 
 3   condition     51525 non-null  object 
 4   cylinders     46265 non-null  float64
 5   fuel          51525 non-null  object 
 6   odometer      43633 non-null  float64
 7   transmission  51525 non-null  object 
 8   type          51525 non-null  object 
 9   paint_color   42258 non-null  object 
 10  is_4wd        25572 non-null  float64
 11  date_posted   51525 non-null  object 
 12  days_listed   51525 non-null  int64  
dtypes: float64(4), int64(2), object(7)
memory usage: 5.1+ MB


Total number of rows: 51525

[Observations]

* missing values (-> Step 2. Data preprocessing)
    <br>o cylinders
* data type conversion (-> Step 2. Data preprocessing)
<br>o date_posted: object -> datetime [express in %Y-%m-%d format so we can perform date calculations if necessary]

In [5]:
# Get some more general info on the quantitative data. 
data.describe()

price    model_year     cylinders       odometer   is_4wd  \
count   51525.000000  47906.000000  46265.000000   43633.000000  25572.0   
mean    12132.464920   2009.750470      6.125235  115553.461738      1.0   
std     10040.803015      6.282065      1.660360   65094.611341      0.0   
min         1.000000   1908.000000      3.000000       0.000000      1.0   
25%      5000.000000   2006.000000      4.000000   70000.000000      1.0   
50%      9000.000000   2011.000000      6.000000  113000.000000      1.0   
75%     16839.000000   2014.000000      8.000000  155000.000000      1.0   
max    375000.000000   2019.000000     12.000000  990000.000000      1.0   

       days_listed  
count  51525.00000  
mean      39.55476  
std       28.20427  
min        0.00000  
25%       19.00000  
50%       33.00000  
75%       53.00000  
max      271.00000

[Observations]

* price (-> Step 4. Carry out exploratory data analysis)
    <br>o min = 1? Vehicles that cost a dollar? A clerical error? The vehicles are so expensive that the sellers do not want to reveal the price? An outlier?
    <br>o The median price is around 9K.
    <br>o At least 25% of the vehicles are sold at no less than 5K.
    <br>o At least 75% of the vehicles are sold at no less than 17K approx.
    <br>o max = 375K. The mean and the median (50%) are quite different. The max value does seem way far off above the upper boundary of the normal range (mean + std = 22,173) and it seems to pull the mean higher. Maybe there are Porsches for sale? An outlier?
<br>

* model_year (-> Step 4. Carry out exploratory data analysis)
    <br>o min = 1908? Vintage cars for collectors?
    <br>o The mean and median (50%) are about 2 years apart, which is not a big difference. 
<br>

* cylinders (-> Step 4. Carry out exploratory data analysis)
    <br>o max = 12!! We have some Lamborghinis on sale here!
    <br>o The mean and median (50%) are very similar. So the max value is not an outlier. 
<br>

* odometer (-> Step 4. Carry out exploratory data analysis)
    <br>o min = 0. Even vehicles fresh out of the factory have some kind of mileage. A clerical error? Sellers hiding an extremely high mileage?
    <br>o max = 990000. Though this seems way far off above the upper boundary of the normal range (mean + std = 180,648), the mean and median are not very different (115553 - 113000. = 1500). So not an outlier? (-> Step 4. Carry out exploratory data analysis)
<br>

* days_listed (-> Step 4. Carry out exploratory data analysis)
    <br>o min = 0. Brand new ads that happen to be placed on the day the report was made?
    <br>o max = 271. The ads have been up for more than 9 months. The vehicles have already been sold and they forgot to take the ads down, or the sellers should give up on selling the workthless cars?
    <br> o The mean and median differ by about 7 days (40 - 33 = 7), which is not too big a difference. So the max is not an outlier?

Let's see what kind of values are there in each column.

Note: skipping this step for 'price', 'odometer', 'date_posted' and 'days_listed' since the lists are too long and cannot spot anomalies this way.

In [6]:
# View the unique values in model_year. 
#data.model_year.unique()

[Observation] Nothing new to add.

In [7]:
# View the unique values in model. 
#data.model.unique()

[Observation] Suspicious - there may be duplicate values (e.g. presence/absence of a hyphen). (-> Step 2. Data preprocessing)

In [8]:
# View the unique values in condition. 
#data.condition.unique()

[Observation] No anomalies. 
<br>Replace string values with a numeric scale. (-> Step 3. Calculate and add to the table the following)
* new = 5
* like new = 4
* excellent = 3
* good = 2
* fair = 1
* salvage = 0

In [9]:
# View the unique values in cylinders. 
data.cylinders.unique()

array([ 6.,  4.,  8., nan,  5., 10.,  3., 12.])

[Observation] Nothing new to add.

In [10]:
# View the unique values in fuel. 
data.fuel.unique()

array(['gas', 'diesel', 'other', 'hybrid', 'electric'], dtype=object)

[Observation] No anomalies.

In [11]:
# View the unique values in transmission. 
data.transmission.unique()

array(['automatic', 'manual', 'other'], dtype=object)

[Observation] No anomalies. I have verified on the web 'other' is OK because there are also other transmission types in addition to "automatic" and "manual". 

In [12]:
# View the unique values in type. 
data.type.unique()

array(['SUV', 'pickup', 'sedan', 'truck', 'coupe', 'van', 'convertible',
       'hatchback', 'wagon', 'mini-van', 'other', 'offroad', 'bus'],
      dtype=object)

[Observation] No anomalies.

In [13]:
# View the unique values in paint_color. 
data.paint_color.unique()

array([nan, 'white', 'red', 'black', 'blue', 'grey', 'silver', 'custom',
       'orange', 'yellow', 'brown', 'green', 'purple'], dtype=object)

[Observation] Nothing new to add.

In [14]:
# View the unique values in is_4wd. 
data.is_4wd.unique()

array([ 1., nan])

[Observation] Replace 'nan' with 'False'. (-> Step2. Data preprocessing)

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
A very good start and first view on data. 

</div>

### Conclusion

[Missing values]
<br>The following variables will be taken care of in "Step 2. Data preprocessing":
* model_year
* odometer
* paint_color
* is_4wd
* cylinders
<br>

[Data type conversion]
<br>The following variables will be taken care of in "Step 2. Data preprocessing":
* model_year
* cylinders
* is_4wd
* date_posted
<br>

[Duplicates]
<br>The following variable will be taken care of in "Step 2. Data preprocessing":
* model
<br>

[Variable renaming]
<br>The following variable will be taken care of in "Step 2. Data preprocessing":
* odometer
<br>

[Categorical to quantitative variable category conversion]
<br>The following variable will be taken care of in "Step 3. Calculate and add to the table the following":
* condition
<br>

[Exploratory data analysis]
<br>The following variables will be the target of further investigation in "Step 4. Carry out exploratory data analysis":
* price
* model_year
* cylinders
* odometer
* days_listed

<div class="alert alert-warning">
<b>Reviewer's comment v1:</b>
       
Additionally `value_counts` method can be used to check data, especially can be helpful to check dublicates in the model column like  `ford f-250 sd` or  `ford f-250 super duty`.

In pandas when we print a dataframe, it displays at max_rows number of rows. If we have more rows, then it truncates the rows. To check the maximum number of rows you can use the following code: 
    
    pandas.options.display.max_rows
  
  To display all rows in the dataframe you need to add the following code, so that this max_rows limitation will be switched off.

    pd.set_option('display.max_rows', None)

</div>

<div class="alert alert-info"> <b>Student comments:</b> That was exactly my problem! In order to see the inconsistencies in 'model' values, I wanted to display the full list but value_counts() abbreviated the middle part due to its length. I will be switching off the max_rows limitation left, right and centre from now on! 

    pd.set_option('display.max_rows', None)
    data.model.value_counts().sort_index(ascending=True)

[Update] Since I switched off the max_rows limitation, I started viewing all the rows in full in every cell where I did not limit it with .head() and .tail() and jupyter hub went into an overdrive! So I have learned that I should use this code in moderation. ;D
    
The other thing was the timing. In order to follow the template in the project descripion, I stopped myself from going in too deep in the section above and left a note that I would be looking into this issue later "(-> Step 2. Data preprocessing)". 
</div>

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
"All columns" function is indeed not required every time, but at the same time I can definetely recomend to always use .sample() or .head() for tables.
</div>

## Data preprocessing

Since it makes my life easier when I take care of missing values, I would like to do the following at this stage:

* rename 'odometer' to 'mileage'
* unify inconsistent naming in 'model'

**Rename variables**

In [15]:
# Rename 'odometer' to 'mileage' for ease of understanding.
data.rename(columns={'odometer':'mileage'}, inplace=True)

# Verify it worked. 
#data.info()

[Observation] From here on, 'odometer' will be referred as 'mileage'.

**Take care of duplicates  in 'model' due to the presence/absence of a hyphen**

During my preliminary exploration of 'mode', I had found the values suspicious and wanted to check properly. So here it is. 

In [16]:
# View the unique values in 'model' in alphabetical order. 
#sorted(data.model.unique())

[Observation] Lo and behold, the inconsistent use of the hyphen caused the same model to be categorised separately. Unify them as follows: 

* 'ford f-150', 'ford f150' -> unify as 'ford f150'
* 'ford f-250', 'ford f250' -> unify as 'ford f250'
* 'ford f-250 sd', 'ford f-250 super duty', 'ford f250 super duty' -> unify as 'ford f250 super duty' 
* 'ford f-350 sd', 'ford f350 super duty' -> unify as 'ford f350 super duty'

In [17]:
# Change 'ford f-150' to 'ford f150'.
data.loc[data['model'] == 'ford f-150', 'model'] = 'ford f150'

# Verify it worked. 
#sorted(data.model.unique())

In [18]:
# Change 'ford f-250' to 'ford f250'.
data.loc[data['model'] == 'ford f-250', 'model'] = 'ford f250'

# Verify it worked. 
#sorted(data.model.unique())

In [19]:
# Change 'ford f-250 sd' and 'ford f-250 super duty' to 'ford f250 super duty'.
data.loc[data['model'] == 'ford f-250 sd', 'model'] = 'ford f250 super duty'
data.loc[data['model'] == 'ford f-250 super duty', 'model'] = 'ford f250 super duty'

# Verify it worked. 
#sorted(data.model.unique())

In [20]:
# Change 'ford f-350 sd' to 'ford f350 super duty'.
data.loc[data['model'] == 'ford f-350 sd', 'model'] = 'ford f350 super duty'

# Verify it worked. 
#sorted(data.model.unique())

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
Ah, great that you identified data with similar car model name!

</div>

<div class="alert alert-info"> <b>Student comments:</b> Yes, I waited until I got here to investigate and take care of the inconsistencies in 'model' because of the template in the project description.</div>  

**Identify and study missing values**

Determine how to fill missing values in such a way that the general characteristics of the dataset are maintained, and fill them.

In [21]:
# View which columns are missing values.
#data.isnull().sum()

Evalute the ratio of the missing values that each variable contributes.
Total number of rows: 51525
* model_year = 3619 / 51525 = 0.070 -> 7%
* cylinders = 5260 / 51525 = 0.10 -> 10%
* mileage = 7892 / 51525 = 0.15 -> 15%
* paint_color = 9267 / 51525 = 0.18 -> 18%
* is_4wd = 25953 / 51525 = 0.50% -> 50%

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
Great that you calculated the percentage of missing values. It helps to understand the overall impact and to make a more weighted decision regarding what to do next.

You can also create a dataframe with missing values using, for example, this code:

    mis_values = data.isnull().sum().to_frame('missing_values')
    mis_values['%'] = round(data.isnull().sum()/len(data),3)
    mis_values.sort_values(by='%', ascending=False)

</div>

<div class="alert alert-info"> <b>Student comments:</b> Nice! I will automate the process from now on. :)</div>  

**Variable: is_4wd**

A 'is_4wd' variable value is missing from 25953 rows.

Possible reasons: data entry was made only when a vehicle was a 4x4. 
<br>Handling method: 'is_4wd' indicates if a vehicle is a 4x4 or not. unique() showed only '1' ('NaN' being the other). Those vehicles that are not marked '1' presumably are not a 4wd. So 'NaN' can be filled with '0'.

In [22]:
# Count the number of non-null values (value of '1'). 
one = data['is_4wd'].value_counts()

# Count the number of null values ('NaN'). 
empty = data['is_4wd'].isnull().sum()

# Print the counts.
print('one', one)
print('empty', empty)

one 1.0    25572
Name: is_4wd, dtype: int64
empty 25953


[Observation] 
* the number of rows with '1': 25572
* the number of rows with 'NaN': 25953
* total: 25572 + 25953 = 51525 -> OK, making sure that the total number adds up to the original dataset. 

In [23]:
# Fill the missing values with a '0'.
data['is_4wd'] = data['is_4wd'].fillna(0)

# Verify it worked. 
#data.is_4wd.unique()
#data.isnull().sum()

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
Indeed, `is_4wd` contains a boolean type of information (yes/no). So filling missing data with 0 will allow us to keep a potentially useful feature.

</div>

<div class="alert alert-info"> <b>Student comments:</b> Again, because of the project template, I felt I had to handle "missing values" and "data type conversion" separately. Otherwise, I would have converted 'is_4wd' here in a single line of code. Will that be acceptable in real life scenario, or doing it in two separate sections the recommended work process?</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>

Yes, it is possible to split these activities (not a strict rule or requirement) and make a data type conversion as a last step before data analysis.
</div>

**Variable: paint_color**

A 'paint_color' variable value is missing from 9267 rows.

Possible reasons: a clerical error during data entry; customers failing to reveal the information
<br>Handling method: the colour of a vehicle is a very subjective matter, and it does not seem possible or right to try and guess to restore the missing values. I do not want to drop the rows with missing values because there is valuable data in other variables in those rows. So 'NaN' can be filled with 'Unknown'.

In [24]:
# Count the number of non-null values. 
#full = data['paint_color'].value_counts()
full = data['paint_color'].notnull().sum()

# Count the number of null values ('NaN'). 
empty = data['paint_color'].isnull().sum()

# Print the counts.
print('full', full)
print('empty', empty)

full 42258
empty 9267


[Observation]

* the number of rows are full: 42258
* the number of rows with 'NaN': 9267
* total: 42258 + 9267 = 51525 -> OK, making sure that the total number adds up to the original dataset.

In [25]:
# Fill the missing values with 'unknown' and store in a new column in order to keep the original raw data.
data['filled_paint_color'] = data['paint_color'].fillna('unknown')

# Verify it worked. 
#data.filled_paint_color.unique()
#data.isnull().sum()

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
That is also correct to fill it with others, as it is not possible to fill this value based on other car features. 
</div>

<div class="alert alert-info"> <b>Student comments:</b> I will make a better choice of word next time so it will be more in context. :)</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>

You did everything correct! By 'others' I meant indeed any word (unknown in your case) that will be filled instead of NaNs.

</div>

**Variable: cylinders**

A 'cylinders' variable value is missing from 5260 rows. 

Possible reasons: a clerical error during data entry; customers failing to reveal the information
<br>Handling method: perhaps, it is possible to know 'cylinders' values from 'model_year' and 'model'.

Let's check. 

In [26]:
# Keep a copy of the original 'cylinders' values just in case, so I will be able to refer to the raw data later as needed. 
cylinders_copy = data['cylinders']

Find the most common value of all the 'cylinder' values for each 'model_year'-'model' pair.

In [27]:
# Get a slice of the 'data' dataframe where 'cylinders' values are not empty to get an accurate mode value. 
cylinders_non_empty = data[data['cylinders'].notnull()]

# View the slice. 
#cylinders_non_empty

<div class="alert alert-warning">
<b>Reviewer's comment v1:</b>
       
It is not necessary to comment last lines with data output, as I am also curious how it looks :) 

You can use `cylinders_non_empty.sample(5)` to get 5 random rows from the data or `cylinders_non_empty.head(5)` or 
`cylinders_non_empty.tail(5)` to get 5 first or last rows.

</div>

<div class="alert alert-info"> <b>Student comments:</b> This is my second project, and in my previous project, the Reviewer advised me to comment out all the checkings that I do in order to make the project file more readable (I tend to check every single thing, as you saw...), so I made sure everything will be hidden...

Regarding limiting the rows to display, I thought to myself, "the view will be automatically limited anyway, so I won't bother with .head(num) and .tail(num), and I'll save myself from typing 8 more characters." Is there an advantage to specifying .head() and .tail() as opposed to freely displaying the preset number of limited rows? 
    
</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>

If some data is used to make a conclusion then it is better to show this data. If not, then indeed comment or delete :) 
Rows are limited in Jupiter notebooks but that is not the case for all tools.

</div>

In [28]:
# Group the slice by 'model_year' and 'model', and find the most common value in 'cylinders'.
cylinders_modes = cylinders_non_empty.groupby(['model_year', 'model'])['cylinders'].agg([pd.Series.mode, 'min'])

# View the dataset.
#cylinders_modes

It looks like there is only one value for each 'model_year'-'model' pair. 
<br>In case there is more than one, apply the mode operation to choose the most common value, 
<br>e.g. for [8.0, 8.0, 6.0], the mode is 8.0. 

In case two values have the same mode, apply the min operation to choose the smaller of the two. I understand that this is the industry standard compromise.
<br>e.g. for [8.0, 6.0], the mode returns [8.0, 6.0], so the min is 6.0. 

[QUESTION] I cannot find a way to leverage 'cylinders_modes' in my line of code with transform(). Could you let me know the correct code?

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
  
For example, smth like this: 
        
    cylinders_non_empty['cylinders'] = cylinders_non_empty['cylinders'].fillna(cylinders_non_empty.groupby('model')['cylinders'].transform('mode'))

</div>

<div class="alert alert-info"> <b>Student comments:</b> I'm afraid the code does not work (I got my tutor's help to confirm my findings). :( transform() does not accept 'mode' (it accepts 'sum' but not 'mode'!), and it needs to be grouped by both 'model_year' and 'model'.  But thank you for trying. </div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
  
Yes, sorry transform only works with categorical values for mode. 
</div>

Let's go ahead and fill the missing values in 'cylinders' with the most common value. 
<br>Prepare a copy of 'model_year' where all the NaN's are replaced with zero. This is to make sure all the variables are of the same size when filling the missing values in 'cylinders' to avoid an error being issued. 
<br>'model' has no missing values to start with and there are 51525 rows in full.

In [29]:
# Fill the missing values in 'model_year' with zero and store in a new column. 
data['zero_filled_model_year'] = data['model_year'].fillna(0)

# Verify it worked.
#data['zero_filled_model_year'].isnull().sum()

In [30]:
# Fill the missing values in 'cylinders' with the corresponding most common value. 
# Take care of the case where mode() returns more than one value by choosing one. 
data['cylinders_mode'] = data.groupby(['zero_filled_model_year', 'model'])['cylinders'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())

In [31]:
# pip install -U pandas

Defaulting to user installation because normal site-packages is not writeable
Requirement already up-to-date: pandas in /home/jovyan/.local/lib/python3.7/site-packages (1.2.5)
Note: you may need to restart the kernel to use updated packages.


[QUESTION] Even using "dropna=False", I get the ""ValueError: Length of passed values is 7, index implies 0", i.e. the code has a problem handling NaNs. Why? (That's why I had used the workaround of 'zero_filled_model_year'.)

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
  
Sorry, not sure where you are getting the error but you can check a nice article how dropna function works here: https://www.w3resource.com/pandas/dataframe/dataframe-dropna.php


</div>

<div class="alert alert-info"> <b>Student comments:</b> I was referring to dropna=False like this:
    
    .groupby(['zero_filled_model_year', 'model'], dropna='False')

My tutor says the code should work but sees that it does not. He suspects that something may have changed on pandas' side in the recent updates. 
</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
  
Ah, yes, most likely Yandex environment has not the latest library versions, so this could cause an issue. 

You can update required library manually. Then it seems to be working. 
    
    # pip install -U pandas

    
</div>

In [ ]:
# Verify it worked. 
data['cylinders_mode'].unique()

[Observation] There are still NaN's. 

In [ ]:
# Check how many NaNs are left. 
data['cylinders_mode'].isnull().sum()

In [ ]:
# View the data where 'cylinders_mode' still contains NaN.
#data[data['cylinders_mode'].isnull()].sort_values(by=['model_year', 'model'])

[Observation] There are 'model_year'-'model' pairs where there is no value in 'cylinders', so the function returned a NaN.

In [ ]:
# Take care of the remaining cases by replacing the missing values with the most common value in 'model'.
#data['cylinders_mode'] = data.groupby('model', dropna=False)['cylinders_mode'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())
data['cylinders_mode'] = data.groupby('model')['cylinders_mode'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())

In [ ]:
# Verify it worked. 
data['cylinders_mode'].unique()

In [ ]:
# Check how many NaNs are left. 
data['cylinders_mode'].isnull().sum()

[Observation] 'cylinders_mode' has now been restored in full. 

I discovered that there are rows where 'cylinders_mode' does not contain the value of 'cylinders' on the same row. 
So as a workaround, I need to copy the value from 'cylinders_mode' only where 'cylinders' contains NaN.

In [ ]:
# Restore the original 'cylinders' into 'cylinders_mode_combined'.
data['cylinders_mode_combined'] = cylinders_copy

# Fill in the missing value if indices match. 
data['cylinders_mode_combined'] = data['cylinders_mode_combined'].fillna(data['cylinders_mode'])

In [ ]:
# Check how many NaNs are left. 
#data['cylinders_mode_combined'].isnull().sum()

**Variable: model_year**

A 'model_year' variable value is missing from 3619 rows.

Possible reasons: a clerical error during data entry; customers failing to reveal the information
<br>Handling method: perhaps, it is possible to know 'model_year' values from 'model' and 'mileage' - the older the model, the higher the mileage.

Let's check. 

In [ ]:
# Keep a copy of the original 'model_year' values just in case, so I will be able to refer to the raw data later as needed. 
model_year_copy = data['model_year']

Find the most common value of all the 'model_year' values for each 'model'-'mileage' pair.

In [ ]:
# Get a slice of the 'data' dataframe where 'model_year' values are not empty to get an accurate mode value. 
model_year_non_empty = data[data['model_year'].notnull()]

# View the slice. 
#model_year_non_empty

In [ ]:
# Group the slice by 'model' and 'mileage', and find the most common value in 'model_year'.
model_year_modes = model_year_non_empty.groupby(['model', 'mileage'])['model_year'].agg([pd.Series.mode, 'min'])

# View the dataset.
#model_year_modes

It looks like there is only one value for each 'model'-'mileage' pair. 

<br>In case there is more than one, apply the mode operation to choose the most common value, 
<br>e.g. for [2018, 2018, 2016], the mode is 2018. 

In case two values have the same mode, apply the min operation to choose the smaller of the two. I understand that this is the industry standard compromise.
<br>e.g. for [2018, 2016], the mode returns [2018, 2016], so the min is 2016. 

[QUESTION] I cannot find a way to leverage 'model_year_modes' in my line of code with transform(). Could you let me know the correct code?

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
  
You can use smth like this. 
    
    model_year_non_empty['model_year'] = model_year_non_empty['model_year'].fillna(model_year_non_empty.groupby('model' ['mileage'].transform('median'))

</div>

Let's go ahead and fill the missing values in 'model_year' with the most common value. 
<br>Prepare a copy of 'mileage' where all the NaN's are replaced with zero. This is to make sure all the variables are of the same size when filling the missing values in 'model_year' to avoid an error being issued. 
<br>'model' has no missing values to start with and there are 51525 rows in full.

In [ ]:
# Fill the missing values in 'mileage' and store in a new column. 
data['zero_filled_mileage'] = data['mileage'].fillna(0)

# Verify it worked.
#data['zero_filled_mileage'].isnull().sum()

In [ ]:
# Fill the missing values in 'model_year' with the corresponding most common value.
# Take care of the case where mode() returns more than one value by choosing one. 
#data['model_year_mode'] = data.groupby(['model', 'zero_filled_mileage'], dropna=False)['model_year'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())
data['model_year_mode'] = data.groupby(['model', 'zero_filled_mileage'])['model_year'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())

[QUESTION] Even using "dropna=False", I get the ""ValueError: Length of passed values is 7, index implies 0", i.e. the code has a problem handling NaNs. Why? (That's why I had to use the workaround of 'zero_filled_mileage'.)

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
  
Again, sorry but i need more info regarding the issue. Could you please reach your tutor in slack to discuss the issue in more detail? 

</div>

<div class="alert alert-info"> <b>Student comments:</b> My tutor is trying to figure out why something that should work is not working. But given the time constraint, since my current code works, I would like to leave it as is and not change it. Hopefully, I will discover something new between this and the next project. </div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
Currently, there is definitely a workable solution. Hopefully, a tutor will be able to support you. 
 
</div>

In [ ]:
# Verify it worked. 
#data['model_year_mode'].unique()

[Observation] There are still NaN's.

In [ ]:
# Check how many NaN's are left. 
data['model_year_mode'].isnull().sum()

In [ ]:
# View the data where 'model_year_mode' still contains NaN.
#data[data['model_year_mode'].isnull()].sort_values(by=['model', 'mileage'])

[Observation] There are 'model'-'mileage' pairs where there is no value in 'model_year', so the function returned a NaN.

[Comment] I should probably categorize 'mileage' into ranges and find the most common value for each 'model'-'mileage_range' pair. But I wanted to be be as precise as possible so I went for the 'mileage' values. I think filling 50012 rows on the first attempt is not bad! :)

In [ ]:
# Take care of the remaining cases by replacing the missing values with the most common value in 'model'-'cylinders' pair.
#data['model_year_mode'] = data.groupby(['model', 'cylinders_mode'], dropna=False)['model_year_mode'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())
data['model_year_mode'] = data.groupby(['model', 'cylinders_mode_combined'])['model_year_mode'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())

In [ ]:
# Verify it worked.
#data['model_year_mode'].unique()

[Observation] There are still NaN's.

In [ ]:
# Check how many NaNs are left.
data['model_year_mode'].isnull().sum()

In [ ]:
# View the data where 'model_year_mode' still contains NaN.
#data[data['model_year_mode'].isnull()].sort_values(by=['model', 'mileage'])

[Observation] This is the only such 'model'-'cylinders' pair of its kind where the 'model_year' information is also not available, and there are no other data yo draw the most common value from.

In [ ]:
# Take care of the remaining case by replacing the missing values with the most common value in 'model' and 'transmission'.
data['model_year_mode'] = data.groupby(['model', 'transmission'])['model_year_mode'].transform(lambda x: x.fillna(x.mode()[0]) if len(x.mode()) == 1 else x.min())

In [ ]:
# Verify it worked.
#data['model_year_mode'].unique()

In [ ]:
# Check how many NaNs are left.
#data['model_year_mode'].isnull().sum()

[Observation] 'model_year_mode' has now been restored in full. 

I discovered that there are rows where 'model_year_mode' does not contain the value of 'model_year' on the same row. 
So as a workaround, I need to copy the value from 'model_year_mode' only where 'model_year' contains NaN.

In [ ]:
# Restore the original 'model_year' into 'model_year_mode_combined'.
data['model_year_mode_combined'] = model_year_copy

In [ ]:
# Fill in the missing value if indices match. 
data['model_year_mode_combined'] = data['model_year_mode_combined'].fillna(data['model_year_mode'])

In [ ]:
# Check how many NaNs are left. 
#data['model_year_mode_combined'].isnull().sum()

**Variable: mileage**

A 'mileage' variable value is missing from 7892 rows.

Possible reasons: a clerical error during data entry; customers failing to reveal the information
<br>Handling method: perhaps, it is possible to make an educated guess for 'mileage' values from 'model' and 'model_year' - the older the model, the higher the mileage, and take the mean or the median.

Let's check. 

In [ ]:
# Keep a copy of the original 'mileage' values just in case, so I will be able to refer to the raw data later as needed. 
mileage_copy = data['mileage']

[Addendum] In creating 'zero_filled_mileage', I checked if there are 0 values in the variable. 

In [ ]:
# View the rows where the 'mileage' value is zero.
#data[data['mileage'] == 0]

[Observation] Though small, there are 185 rows that do not offer any information on the mileage. Whatever the reason as to why these rows contain 0, I want to keep them as they are to see how missing information on mileage will affect the vehicle price. 

Check which is better to use to fill the missing values in 'mileage' - the mean or the median.

In [ ]:
# Group the dataset by 'model_year' and 'model' and display the mean values of 'mileage'.
mileage_mean = data.groupby(['model_year_mode_combined', 'model'])['mileage'].mean()

#View the result.
#mileage_mean

In [ ]:
# Group the dataset by 'model_year' and 'model' and display the mean values of 'mileage'.
mileage_median = data.groupby(['model_year_mode_combined', 'model'])['mileage'].median()

#View the result.
#mileage_median

[Observation] The mean and median are very similar for most of the 'model_year'-'model' pairs. In the above short list, the median is a little higher than the mean for "ford f150". 

Since describe() shows us that the mean (115553.461738) is higher than the median (113000), probably being pulled up by the max (990000), I think it will be safer to use the median to fill the missing values. 

In [ ]:
# Get a slice of the 'data' dataframe where 'mileage' values are not empty to get an accurate median value. 
mileage_non_empty = data[data['mileage'].notnull()]

# View the slice. 
#mileage_non_empty

In [ ]:
# Group the slice by 'model_year' and 'model', and find the most common value in 'odometer'.
#mileage_with_mode = mileage_non_empty.groupby(['model', 'mileage'])['mileage'].mean().to_frame()
mileage_medians = mileage_non_empty.groupby(['model_year_mode_combined', 'model'])['mileage'].agg('median')

# View the dataset.
#mileage_medians

[Observation] In the above short list, the values are exactly the same as the one including NaNs from earlier. 

Let's go ahead and fill the missing values in 'mileage' with the median. 
<br>Use 'model_year_mode' which have no missing values. This makes sure all the variables are of the same size when filling the missing values in 'mileage' to avoid an error being issued. 
<br>'model' has no missing values to start with and there are 51525 rows in full. 

In [ ]:
# Fill the missing values in 'mileage' with the corresponding median value. 
data['mileage_median'] = data.groupby(['model_year_mode_combined', 'model'])['mileage'].transform(lambda x: x.fillna(x.median()))

In [ ]:
# Verify it worked. 
data['mileage_median'].isnull().sum()

In [ ]:
# View the data where 'mileage_median' still contains NaN.
#data[data['mileage_median'].isnull()].sort_values(by=['model_year_mode_combined', 'model'])

[Observation] There are 'model_year'-'model' pairs where there is no value in 'mileage', so the function returned a NaN.

In [ ]:
# Take care of the remaining cases by replacing the missing values with the median in 'model_year' and 'cylinders'.
data['mileage_median'] = data.groupby(['model_year_mode_combined', 'cylinders_mode_combined'])['mileage_median'].transform(lambda x: x.fillna(x.median()))

In [ ]:
# Verify it worked. 
data['mileage_median'].isnull().sum()

[Observation] There is still 1 NaN.

In [ ]:
# View the data where 'mileage_median' still contains NaN.
#data[data['mileage_median'].isnull()].sort_values(by=['model_year_mode_combined', 'model'])

In [ ]:
# Take care of the remaining cases by replacing the missing values with the median in 'model' and 'cylinders'.
data['mileage_median'] = data.groupby(['model', 'cylinders_mode_combined'])['mileage_median'].transform(lambda x: x.fillna(x.median()))

In [ ]:
# Verify it worked. 
#data['mileage_median'].isnull().sum()

[Observation] 'mileage' has now been restored in full. 

I discovered that there are rows where 'mileage_median' does not contain the value of 'mileage' on the same row. 
So as a workaround, I need to copy the value from 'mileage_median' only where 'mileage' contains NaN.

In [ ]:
# Restore the original 'mileage' into 'mileage_median_combined'.
data['mileage_median_combined'] = mileage_copy

In [ ]:
# Fill in the missing value if indices match. 
data['mileage_median_combined'] = data['mileage_median_combined'].fillna(data['mileage_median'])

In [ ]:
# Check how many NaNs are left. 
#data['mileage_median_combined'].isnull().sum()

**Convert the data to the required types**

'NaN' is of type float and cannot be converted to an int type. While the rows contain 'NaN'as missing values, the datatype of the variable cannot be changed to int. Now that the missing values have been taken care of, I can proceed with data type conversion. 

Note: where the original variables still contain NaN, its counterparts will be put through data type conversion:
* original: model_year -> counterparts: zero_filled_model_year, model_year_mode
* original: cylinders -> counterparts: zero_filled_cylinders, cylinders_mode

In [ ]:
#data.info()

In [ ]:
# Convert the data type of 'model_year' from float to int.
# Reason: no such thing as "a 2021.5 model" so it makes better sense.
data['zero_filled_model_year'] = data['zero_filled_model_year'].astype(np.int64)
data['model_year_mode'] = data['model_year_mode'].astype(np.int64)
data['model_year_mode_combined'] = data['model_year_mode_combined'].astype(np.int64)

In [ ]:
# Convert the data type of 'cylinders' from float to int.
# Reason: no such thing as "4.6 cylinders" so it makes better sense.
data['cylinders_mode'] = data['cylinders_mode'].astype(np.int64)
data['cylinders_mode_combined'] = data['cylinders_mode_combined'].astype(np.int64)

In [ ]:
# Convert the data type of 'is_4wd' from float to boolean. 
# Reason: it's either a 4wd or not. 
data['is_4wd'] = data['is_4wd'].astype(bool)

In [ ]:
# Verify it worked.
#data.info()

In [ ]:
# Convert the data type of 'date_posted' from object to date in %Y-%m-%d format.
# Reason: so we can perform date calculations if necessary.
data['date_posted'] = pd.to_datetime(data['date_posted'], format='%Y-%m-%d')

# Verify it worked.
#data.date_posted.head(10)

<div class="alert alert-success">
<b>Reviewer's comment v1:</b>

Well done that you have checked and correctly replaced the data types.

</div>

**Investigate logically unsound values**

**Variable: price**

In 2020, the average price of a second hand car in the USA was 22,000. In our dataset, the mean is about 12132 and the median, 9000. So the minimum of 1 and the maximum of 375000 do seem off the chart. 

Let's check.

In [ ]:
# Let's find some extreme cases where the 'model_year' is recent and yet the 'price' is ludicrously low. 
#data[(data['price'] < 10) & (data['model_year'] > 2010)].sort_values(['price', 'model_year'])

<div class="alert alert-warning">
<b>Reviewer's comment v1:</b>
       
Once again it is better not to hide results of your research from others.

</div>

<div class="alert alert-info"> <b>Student comments:</b> Yes, I was following an advice from my previous Reviewer...I guess it depends on the Reviewer's preference. I will take my chances in my next project by showing all my findings. </div>  

<div class="alert alert-success">
<b>Reviewer's comment v2:</b>

Hmm, if data is used for the conclusion below, then definitely show (head() or sample()). 
If you want to quickly check smth (not important, no impact on the project structure) then even better delete it or comment.

</div>

[Observation] Who will sell a 2018 jeep wrangler that is in excellent condition that has only done 3420 (miles, assuming that this is data about the USA?) in mileage for a dollar? Filtering with 'price' < 10 and 'model_year' > 2010, and there are already 693 such rows. There is too much data with unreasonable prices for them to be clerical errors - I think these are intentional (MNAR). 

As I have seen with house sale ads, it is possible that the sellers did not want to reveal the high asking price so as not to scare the potential buyers. Another possibility is that the sellers are lying about the condition and the cars are actually totalled and not drivable. 

I am leaving them intact.

So what about extremely high prices?

In [ ]:
# Let's find some extreme cases where the 'model_year' is recent and yet the 'price' is ludicrously low. 
#data[data['price'] > 150000].sort_values('price', ascending=False)

[Observation] A used Ferrari 250 GTO apparently can cost at least $38 million in cash. 

According to my brief research on the web, below are the price ranges/high end prices (in USD) for the used cars in the table above: 
* nissan frontier 1999: 392 to 8000
* RAM 2500 2015: 17,272 to 29,998
* ford f-150 2014: 18,955 to 34,991
* gmc sierra 2500hd 2004: 1,140 to 17,022

So the only anomaly in the table is the 1999 nissan frontier. It is possible that it is a human error. I am guessing that 375000 should be changed to 3750. 

In [ ]:
# Change the price of '1999 nissan frontier' to 3750, assuming a clerical error.
data.loc[data['price'] == 375000, 'price'] = 3750

# Verify it worked. 
#data[(data['model'] == 'nissan frontier') & (data['model_year'] == 1999)]

**Variable: days_listed**

On the surface, the following values do not seem alarming:
* min days_listed = 0 -> totally reasonable that the dataset was created on the very day that the ads were placed
* max days_listed = 271 -> totally reasonable that the ads have been up for 9 months. Maybe someone forgot to take them down or the vehicles still have found no buyers.

Let's check. 

In [ ]:
# View the data where 'days_listed' = 0 and check the values in other columns if it makes sense. 
#data[data['days_listed'] == 0]

[Observation] even if days_listed = 0, the date_posted values are all different. 

In [ ]:
# Count how many such rows there are. 
#data[data['days_listed'] == 0].count()

[Observation] There are 54 such rows. 

In [ ]:
# Try adding 'date_posted' and 'days_listed' and see what happens.
temp = data['days_listed'].apply(np.ceil).apply(lambda x: pd.Timedelta(x, unit='D'))
data['removal_date'] = data['date_posted'] + temp

# View the result. 
#data

[Observation] They all come to different dates. I think 'days_listed' shows how many days it took for the vehicles to sell since the ad was placed. Where a zero is registered, there was probably some kind of error in the system and the 'days_listed' values were not calculated. 

No actual ad removal dates are provided, so I can only make an educated guess at with what value to recalculate where 'days_listed' = 0.

In describe(), the mean is 39.6 and the median is 33. I will use the mean value to fill the zero entries as I found out when investigating about the max value (271) that selling a vehicle usually takes very long. 

In [ ]:
# Replace 0 in 'days_listed' with the mean taken from describe().
mean = int(39.55476)
data.loc[data['days_listed'] == 0, 'days_listed'] = mean

# Verify it worked.
#data[data['days_listed'] == 0].count()

In [ ]:
# View the data where 'days_listed' are close to the max value, 271.
# Check the values in other columns if it makes sense. 
#data.sort_values('days_listed', ascending=False)

[Observation] 271 does not seem to be that much of an exception. There are more rows with similar value. 

In [ ]:
# Check how many rows there are where 'days_listed' is more than the average of 39 days. 
#data[data['days_listed'] > 39].count()

[Observation] There are 20908 rows for above 39 days. That is 40.6% of the total (= 20908 / 51525). I found a reference on the web that a professional second hand auto dealer is said to take at least 60 days to sell a used car. So the max value of 271 and others similar to it are OK. 

**Take care of duplicates**

In [ ]:
# Look for duplicate rows where they are identical column for column. 
data.duplicated().sum()

[Observation] There are no such rows. 

Those rows which are identical in the values of:
* mileage
* model_year
* model
* cylinders
* fuel
* transmission
* type
* is_4wd
* price

indicate the same ad being activated repeatedly since it was first placed. 

[Side comment] It may be interesting to investigate if there is a relationship between the number of times the same ad was placed and the sale price, but that is for another research. 

In [ ]:
#Look for duplicate rows which are identical in the columns listed above.
#duplicates = data[data.duplicated(subset = ['mileage', 'model_year', 'model', 'cylinders', 'fuel', 'transmission', 'type', 'is_4wd', 'price'], keep = False)]
#duplicates.sort_values(by=['mileage', 'model_year', 'model', 'cylinders', 'fuel', 'transmission', 'type', 'is_4wd', 'price'], ascending=False)

[Observation] These are the same ads that were reactivated repeatedly. However, if the repeated rows were to be removed, this consitutes 27% (= 13788 / 51525) of the whole dataset, which is a large percentage. Without investigating how many times each ad was reactivated, it is unknown how many of these rows will be removed as duplicates, which is a lot of data lost. Besides, each row contains a different value in 'days_listed', which is one of the main targets of the research in this project. So I am going to leave these in for now. 

<div class="alert alert-success">
<b>Reviewer's comment v1:</b>

That is a very interesting observation regarding reactivated users.

</div>

## Make calculations and add them to the table

**Day of the week, month, and year the ad was placed**

In [ ]:
# 'date_posted' is currently in %Y-%m-%d format. 
# Calculate the day of the week and store in a new column.
data['day_of_week'] = pd.DatetimeIndex(data['date_posted']).dayofweek

# Verify it worked. 
#data['day_of_week'].unique()

In [ ]:
# Calculate the month and store in a new column.
data['month'] = pd.DatetimeIndex(data['date_posted']).month

# Verify it worked. 
#data['month'].unique()

In [ ]:
# Calculate the year and store in a new column.
data['year'] = pd.DatetimeIndex(data['date_posted']).year

# Verify it worked. 
#data['year'].unique()

**The vehicle's age (in years) when the ad was placed**

[Disclaimer] Here, I have to calculate the age of a vehicle in the absence of the VIN number. So, I am going to assume that the 'model_year' is the year during which the vehicle was manufactured, though in reality, this is not necessarily the case. 

In [ ]:
# Calculate the vehicle's age by subtracting 'model_year_mode_combined' from 'year' and store in a new column.
data['age'] = data['year'] - data['model_year_mode_combined'] + 1

# Verify it worked. 
#data['age'].unique()

<div class="alert alert-warning">
<b>Reviewer's comment v1:</b>
    
It is also possible to add  +1 to the equation above to take into account the current year. Otherwise, it will lead to multiple 0 in `age` (as below) and as a result infinite values in `mileage_annual_average`. 

</div>

<div class="alert alert-info"> <b>Student comments:</b> OK, I added 1 to account for the current year in the cell above. 

* This gets rid of the cases where 'age' = -1, so I deleted the obsolete cells below.
* There are still cases where 'age' = 0 because -1 + 1 = 0. So, I am going to take care of that next.
</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
Yes, or delete / take abs() of negative values first and then perform calculation. 

</div>

In [ ]:
# Check where there is 0.
#data.query('age == 0')

[Observation] There are 6 rows where 'age' = 0. These will cause a problem later on when I have to calculate the average annual mileage because I will then be dividing by zero. 

I would like to change these to 1. 

In [ ]:
# Before I make any modifications, check how many rows contain 1.
#data.query('age == 1').count()

[Observation] 2212 rows contain 1. Together with the 6 rows where 'age' = 0, the total number of rows containing 1 will be 2218. 

I do not think this is considered as changing the general characteristics of the data because when you take into account the reality, an age of 0 does not make logical sense, and also, they will cause a problem later on when I have to calculate the average annual mileage because I will then be dividing by zero. 

In [ ]:
# Modify 0 to 1 in 'age'. 
data.loc[data['age'] == 0, 'age'] = 1

# Verify it worked.
#data['age'].unique()

[Observation] No more illogical 'age' values. 

**The vehicle's average mileage per year**

The vehicle's average mielage per year is calculated by dividing 'mileage' by 'age'. This will be a problem for those records where 'age' = 0, meaning the ad was placed in the same year as the 'model_year' of the car on sale, because the result will be "undefined". 

In [ ]:
# Calculate by dividing 'mileage' by 'age' and store in a new column.
data['mileage_annual_average'] = data['mileage_median_combined'] / data['age']

In [ ]:
# Check the descriptive statistics that the figures are sound.
#data.describe()

**In the condition column, replace string values with a numeric scale:**
* new = 5
* like new = 4
* excellent = 3
* good = 2
* fair = 1
* salvage = 0

In [ ]:
# Create a dictionary for the list above. 
cat_to_num_dict = {'new': 5, 'like new': 4, 'excellent': 3, 'good': 2, 'fair': 1, 'salvage': 0}

# Verify it works.
#cat_to_num_dict

In [ ]:
# Apply the dictionary to the 'data' dataframe to effect the conversion and store in a new column. 
data['condition_num'] = data['condition'].map(cat_to_num_dict)

# Verify it worked. 
#data['condition_num'].unique()


<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
Great! Now the data has been prepared and ready for the following analysis.

</div>

## Carry out exploratory data analysis

From looking at the descriptive statistics at the start of the project, I already know that the raw data contains high positive values, which are far from where the majority of the data are. For that reason, I am going to study the histograms with the help of the descriptive statistics. 

In [ ]:
# Print out the descriptive statistics here again for convenience. 
data.describe()

= Study the following parameters: price, vehicle's age when the ad was
placed, mileage, number of cylinders, and condition. Plot histograms for
each of these parameters. Study how outliers affect the form and
readability of the histograms. =

**Study 'price'**

In [ ]:
# Plot a histogram. 
data.hist('price', figsize=(10, 6), bins=100, color='pink', grid=True);

# x-axis: shows the price values
# y-axis: shows the number of vehicles

-* Study how outliers affect the form and readability of the histogram. *-

* The high positive values reach as far as 300,000 on the x-axis, causing a heavy tale and creating a positively skewed distribution (skewed to the right), pushing the majority of the values to the left hand side between 0 and 50,000. 
* The graph is trying to fit in the 'lump' on the left in a very few bins, while balancing it with displaying the range of values from min to max in its entirety, making each interval too large to display values in appropriately fine detail. 

These make it difficult to see what is exactly happening in that 'lump'. 

In [ ]:
# To view the area of the histogram where there is most data, we can zoom in by using range.
data.hist('price', figsize=(10, 6), bins=100, color='pink', grid=True, range=(0, 100000));

-* Determine the upper limits of outliers, remove the outliers and store them in a separate DataFrame, and continue your work with the filtered data. *-

In [ ]:
# Determine the upper limit of outliers.
IQR = data['price'].quantile(0.75) - data['price'].quantile(0.25)
price_upper_limit = data['price'].quantile(0.75) + IQR * 1.5

# View the upper limit.
price_upper_limit

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
data['price'].plot.box();

[Observation] Because of all the outliers above the upper limit, the box is very much squashed. 

(I know the instruction does not say I should draw a boxplot but I was curious...)

In [ ]:
# Remove the outliers and store them in a separate DataFrame.
price_without_outliers = data.query('price < @price_upper_limit')

# View the new dataframe.
#price_without_outliers

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
Well done! You perfectly identified and handled outliers. You can additionally check a nice article about working with outliers (based on the similar code you used):
- https://www.pluralsight.com/guides/cleaning-up-data-from-outliers
</div>

[Observation] The total number of rows is now 49876. That means 5% (= 49876 / 51525) account for outliers. 

-* Use the filtered data to plot new histograms. Compare them with the earlier histograms (the ones that included outliers). Draw conclusions for each histogram. *-

In [ ]:
# Plot a new histogram. 
price_without_outliers.hist('price', figsize=(10, 6), bins=100, color='pink', grid=True);

[Comment] I used the same number of bins for both histograms so we can compare the two fairly on the same footing. 

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
B = price_without_outliers['price'].plot.box()

[QUESTION] The calculation told us that 34,587.50 is the upper limit. But after removing the high outliers, the boxplot still shows values above its max line. 

Why is that?

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
  
After removing outliers new boxplot will be created against new values in the dataset with a maximum value 32257.5 as visible on the box plot above. In the new dataset we have multiple values that are lying within or a little bit above a new range.
</div>

<div class="alert alert-info"> <b>Student comments:</b> Understood. 

    IQR = price_without_outliers['price'].quantile(0.75) - price_without_outliers['price'].quantile(0.25)
    price_upper_limit = price_without_outliers['price'].quantile(0.75) + IQR * 1.5

    where price_upper_limit = 32257.5
    
Just out of curiosity, could you let me know how you accessed the stats in the 'AxesSubplot' object (which you assigned to B)? I imported boxplot_stats but B['whiskers'] gives 'the 'AxesSubplot' object is not subscriptable' error message. 

</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
So, one thing you need to add (return_type='dict'). 'dict' returns a dictionary with values of the boxplot that we can access.
    
    B = price_without_outliers['price'].plot.box(return_type='dict')

Then you can access data using this code: 
    
        [item.get_ydata()[1] for item in B['whiskers']] - to get range 
        B['whiskers'][1].get_ydata()[1] - to get max value
 
</div>

[Comparison and Conclusions] 
* The presence of outliers in the data clouds your ability to understand the data. Removing extreme values clears up the clutter and allows you to zoom in on the crux of the data. 
* Visualization so elloquently represents the essence of the saying, "a picture is worth a 1000 words". A spacial representation gives you a big picture and placing landmarks such as a 5-number summary inside that representation helps you get oriented in the sea of data. 

In the new histogram (and boxplot), the distribution is much more spread out, and we can see its details better. 
* Most used car prices fall roughly between 5000 and 15000. This was hard to see in the previously. 
* The average decreased by about 35% (from 12125.259680 to around 8000). 
* The peak at around 10000 that was in the preivous histogram has been split up into many peaks in the new histogram. All the values that had been lumped up together have been spread out to reveal their details.  
* With the same number of bins (100), the curve of the new histogram is less smooth than the previous one, with peaks and troughs repeated every 1000 or so.
* The skewness is still to the right, but not as exaggerated as before. 
* The median is still around 8000 (it was 9000 before according to the descriptive statistics). Q1 and Q3 also have not moved much (they were 5000 and 16835 before, respectively), showing their robustness to the presence and absence of outliers. 

**Study 'vehicle's age when the ad was placed**

In [ ]:
# Plot a histogram. 
data.hist('age', figsize=(10, 6), bins=100, color='pink', grid=True);

# x-axis: shows the vehicle age
# y-axis: shows the number of vehicles

-* Study how outliers affect the form and readability of the histogram. *-

* Since the max age is 110 and the histogram tries to show all the data in a single space, most data appears bunched up on the left side of the graph between 1 and 35, and not much detail can be gotten out of it. 
* Some cars are old and their high 'age' values cause a heavy tail and the histogram to be positively skewed. 
* There is a sharp peak at around 1. This must the -1, 0, 1 values combined into 'age' = 1. The number is too high for them to be outliers, but because they are lumped together, it is difficult to discern what they constitute of. 

In [ ]:
# To view the area of the histogram where there is most data, we can zoom in by using range.
data.hist('age', figsize=(10, 6), bins=100, color='pink', grid=True, range=(0, 60));

-* Determine the upper limits of outliers, remove the outliers and store them in a separate DataFrame, and continue your work with the filtered data. *-

In [ ]:
# Determine the upper limit of outliers.
IQR = data['age'].quantile(0.75) - data['age'].quantile(0.25)
age_upper_limit = data['age'].quantile(0.75) + IQR * 1.5

# View the upper limit.
age_upper_limit

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
data['age'].plot.box();

[Observation] Because of all the outliers above the upper limit, the box is very much squashed.

In [ ]:
# Remove the outliers and store them in a separate DataFrame.
age_without_outliers = data.query('age < @age_upper_limit')

# View the new dataframe.
#age_without_outliers

[Observation] The total number of rows is now 49222. That means 4%% (= 49222 / 51525) account for outliers. 

-* Use the filtered data to plot new histograms. Compare them with the earlier histograms (the ones that included outliers). Draw conclusions for each histogram. *-

In [ ]:
# Plot a new histogram. 
age_without_outliers.hist('age', figsize=(10, 6), bins=100, color='pink', grid=True);

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
age_without_outliers['age'].plot.box();

[Comparison and Conclusions] 

* The shapes of the two histograms are have a certain resemblance in terms of the first and the third peaks, the first bar not being at 0 on the x-axis, and the outline of its positively skewed shape, though the second peak from the previous histogram is less pronounced in the new one. 
* Since 'age' is a discrete variable, we can see the individual values separately, spread out without touching each other in the new histogram. This indicates that the bins are an appropriate size. 
* The sharp peak almost reaching the 7000 vehicle mark in the previous histogram has decreased to around 4200. This is probably due to the single peak being an aggregate of several peaks, and the finer-grain x-axis is able to show the constituent peaks individually. 
* Even after the high outliers have been removed, the median (7), Q1 (4) and Q3 (12) have not changed. 

**Study mileage**

In [ ]:
# Plot a histogram. Display true values on the axis and not in the 1e6 exponential form. 
data.hist('mileage_median_combined', figsize=(10, 6), bins=100, color='pink', grid=True);
plt.ticklabel_format(style = 'plain')

# x-axis: shows the mileage
# y-axis: shows the number of vehicles

-* Study how outliers affect the form and readability of the histogram. *-

* Because of the large range occupied by the outliers, the rest of the values are squashed into the space between 0 and 30000. It is difficult to see the details. 
* There are some extremely well-traveled vehicles. They cause a heavy tail and the histogram to be positively skewed. 
* There are several peaks, the tallest being around 130000, but the values are clumped up together and we cannot see their details. 
* The last values I can discern are those around 50000. I am sure there are more values after that since the x-axis extends beyond 1000000 (in python we trust!)but I cannot make them out. 

In [ ]:
# To view the area of the histogram where there is most data, we can zoom in by using range.
data.hist('mileage_median_combined', figsize=(10, 6), bins=100, color='pink', grid=True, range=(0, 500000));

-* Determine the upper limits of outliers, remove the outliers and store them in a separate DataFrame, and continue your work with the filtered data. *-

In [ ]:
# Determine the upper limit of outliers.
IQR = data['mileage_median_combined'].quantile(0.75) - data['mileage_median_combined'].quantile(0.25)
mileage_upper_limit = data['mileage_median_combined'].quantile(0.75) + IQR * 1.5

# View the upper limit.
mileage_upper_limit

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
# Display true values on the axis and not in the 1e6 exponential form.
data['mileage_median_combined'].plot.box();
plt.ticklabel_format(useOffset=False, style='plain', axis='y')

[Observation] Because of all the outliers above the upper limit, the box is very much squashed.

In [ ]:
# Remove the outliers and store them in a separate DataFrame.
mileage_without_outliers = data.query('mileage_median_combined < @mileage_upper_limit')

# View the new dataframe.
#mileage_without_outliers

[Observation] The total number of rows is now 50864. That means about 1% (= 50864 / 51525) account for outliers. 

-* Use the filtered data to plot new histograms. Compare them with the earlier histograms (the ones that included outliers). Draw conclusions for each histogram. *-

In [ ]:
# Plot a new histogram. 
mileage_without_outliers.hist('mileage_median_combined', figsize=(10, 6), bins=100, color='pink', grid=True);

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
mileage_without_outliers['mileage_median_combined'].plot.box();

[Comparison and Conclusions] 

* With the high outliers gone, the new histogram has spread out almost symmetrically with only a slight skew to the right. It indicates a fairly even distribution with vehicles doing all sorts of mileage between 0 and around 280000. 
* The peak around 0 is much more pronounced, sticking out like a sore thumb in the new histogram. This includes those ads that did not provide mileage information, and (undrivable) vehicles being sold at almost nothing. 
* There are a few peaks between 90000 and 150000. These, and the peak around 0, will flatten out if I were to increase the number of bins. But conversely, more small peaks will appear providing too much detail, and that is a trade off. 
* Even after the high outliers have been removed, the median (113893), Q1 (72926) and Q3 (152000) have not changed. The min has not moved. The max has drastically been reduced from 990000 previously to about 280000. 

**Study number of cylinders**

In [ ]:
# Plot a histogram. 
data.hist('cylinders_mode_combined', figsize=(10, 6), bins=100, color='pink', grid=True);

# x-axis: shows the number of cylinders
# y-axis: shows the number of vehicles

-* Study how outliers affect the form and readability of the histogram. *-

* The number of cylinders are expressed in terms of a small finite discrete set of integers between 3 and 12. The variable cannot take on some unpredictable, unexpected values. That means that the edge values will not be far away enough from where the majority of the data are, to the extent that they can have a significant effect on the shape of the histogram. So, I do not think 3 and 12 (or even 10) can be considered as outliers.   
* The histogram is skewed to the right, with a short tail. 
* Because the number of values displayed on the x-axis is only 7, the histogram manages very well to display the data in its entirety. 

-* Determine the upper limits of outliers, remove the outliers and store them in a separate DataFrame, and continue your work with the filtered data. *-

In [ ]:
# Determine the upper limit of outliers.
IQR = data['cylinders_mode_combined'].quantile(0.75) - data['cylinders_mode_combined'].quantile(0.25)
cylinders_upper_limit = data['cylinders_mode_combined'].quantile(0.75) + IQR * 1.5

# View the upper limit.
cylinders_upper_limit

[Observation] Numbers do not lie - but it is interesting that the calculated upper limit exceeds the max value of 12 in the descriptive statistics. In the listing, there are no 14-cylinder vehicles on sale. 

[QUESTION] Why does this happen?

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
data['cylinders_mode_combined'].plot.box();

[Observation] The boxplot concurs that there are no outliers, too. 

It is interesting that the max line is around 12 and not 14. 

[QUESTION] Does .plot.box() use a different algorithm to calculate the upper limit? 

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>

It can be indeed different based on the quartile calculation method. 
    
        np.percentile(data['cylinders_mode_combined'], [100])  - this will result in value 12
    
</div>

<div class="alert alert-info"> <b>Student comments:</b> Goodness, this is so much more efficient than the method with quantile() that we learned!</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
😅 in this case it is more a matter of taste.

</div>

Remove the outliers and store them in a separate DataFrame.

I do not think there are outliers, but I will remove the data on 3 and 12-cylinder vehicles to see how the shape of the histogram and boxplot will change. 
<br>Note: I am going to "veto" the value of 'cylinders_upper_limit', 14, and use the correct value, 12, to get a correct histogram. 

In [ ]:
cylinders_mode_without_outliers = data.query('cylinders_mode_combined > 3 and cylinders_mode_combined < 12')

# View the new dataframe.
#cylinders_mode_without_outliers

[Observation] The total number of rows is now 51489. That means less than 0.1% account for "outliers". 

-* Use the filtered data to plot new histograms. Compare them with the earlier histograms (the ones that included outliers). Draw conclusions for each histogram. *-

In [ ]:
# Plot a new histogram. 
cylinders_mode_without_outliers.hist('cylinders_mode_combined', figsize=(10, 6), bins=100, color='pink', grid=True);

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
cylinders_mode_without_outliers['cylinders_mode_combined'].plot.box();

[Observation] The min and Q1 now coincide. 

[Comparison and Conclusions] 

* The removal of the edge values (3 and 12) had no added-value to the new histogram. 
* On the contrary, I think we lost valuable data by removing those two values.
* As the boxplot showed us, 3 and 12 were not considered "outliers". 

**Study condition**

In [ ]:
# Plot a histogram. 
data.hist('condition_num', figsize=(10, 6), bins=100, color='pink', grid=True);

# x-axis: shows the condition of vehicles on the scale of 0 to 5
# where new = 5, like new = 4, excellent = 3, good = 2, fair = 1, salvage = 0
# y-axis: shows the number of vehicles

-* Study how outliers affect the form and readability of the histogram. *-

* The condition scale is expressed in terms of a small finite discrete set of integers between 0 and 5. The variable cannot take on some unpredictable, unexpected values. That means that the edge values will not be far away enough from where the majority of the data are, to the extent that they can have a significant effect on the shape of the histogram. So, I do not think 0 and 1 on the low end, and 5 on the high end can be considered as outliers.
* The shape of the histogram is fairly symmetrical with the mid-range condition levels being the most popular. 
* Because the number of values displayed on the x-axis is only 6, the histogram manages very well to display the data in its entirety. 

-* Determine the upper limits of outliers, remove the outliers and store them in a separate DataFrame, and continue your work with the filtered data. *-

In [ ]:
# Determine the upper limit of outliers.
IQR = data['condition_num'].quantile(0.75) - data['condition_num'].quantile(0.25)
condition_upper_limit = data['condition_num'].quantile(0.75) + IQR * 1.5

# View the upper limit. Round up to the nearest whole number. 
np.ceil(condition_upper_limit)

[Observation] As expected.

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
data['condition_num'].plot.box();

[Observation] So the boxplot thinks that 0 and 5 are outliers. 

The median coincides with the Q3. 

In [ ]:
# Confirm in the descriptive statistics that the median coincides with the Q3. 
#condition_num_without_outliers.describe()

Remove the outliers and store them in a separate DataFrame.

In [ ]:
condition_num_without_outliers = data.query('condition_num > 0 and condition_num < @condition_upper_limit')

# View the new dataframe.
#condition_num_without_outliers

[Observation] The total number of rows is now 51267. That means less than 1% (= 51267 / 51525) account for "outliers". 

-* Use the filtered data to plot new histograms. Compare them with the earlier histograms (the ones that included outliers). Draw conclusions for each histogram. *-

In [ ]:
# Plot a new histogram. 
condition_num_without_outliers.hist('condition_num', figsize=(10, 6), bins=100, color='pink', grid=True);

In [ ]:
# Draw a boxplot to see the shape of the distribution, including the outliers and their upper limit.
condition_num_without_outliers['condition_num'].plot.box();

[Observation] The median and Q3 still coincide. 

[Comparison and Conclusions] 

* The removal of the edge values (0 and 5) did not have any added-value to the new histogram. 
* On the contrary, I think we lost valuable data by removing those two values.

= Study how many days advertisements were displayed (days_listed). Plot a histogram. Calculate the mean and median. Describe the typical lifetime of an ad. Determine when ads were removed quickly, and when they were listed for an abnormally long time. =

-* Study how many days advertisements were displayed (days_listed). Plot a histogram. *-

In [ ]:
# Plot a histogram.
data.hist('days_listed', figsize=(10, 6), bins=100, color='pink', grid=True);

# x-axis: shows the number of days an ad was listed
# y-axis: shows the number of ads for each number of listing days 

In [ ]:
# Complement with descriptive statistics...
data.describe()

In [ ]:
#...and with a boxplot.
data['days_listed'].plot.box();

In [ ]:
# Period covered
start = data['date_posted'].min()
end = data['date_posted'].max()
num_of_days = end - start
print('start:', start)
print('end:', end)
print('number of days:', end - start)

Study how many days advertisements were displayed (days_listed).

For the period from 2018-05-01 to 2019-04-19 (353 days), 
* a total of 51525 ads were placed.
* ads were listed for anywhere between 1 day to 271 days. 
* most ads were removed within 20 to 40 days.
* Longer ads are increasingly rare.  

-* Calculate the mean and median. *-

The descriptive statistics tell us:
* mean: 39.5 -> 40 days approx.
* median: 33 days

And now calculate the values in code.

In [ ]:
# Calculate the mean and median.
mean = np.ceil(data['days_listed'].mean())
median = data['days_listed'].median()

print('mean:', mean, 'days')
print('median:', median, 'days')

-* Describe the typical lifetime of an ad. *-

I would say, in this project with 51525 records:
* an ad on average spends about 40 days on the listing until it is removed, 
* however, an ad most likely will be removed after 33 days. 

-* Determine when ads were removed quickly, and when they were listed for an abnormally long time. *-

Assumption:
* "quickly removed ads" can be defined as those with 'days_listed' values that are less than the lower quartile (Q1) and greater than the minimum, and
* "ads which were listed for an abnormally long time" can be defined as those with 'days_listed' values that are greater than the maximum

**quickly removed ads**

In [ ]:
# In the decriptive statistics, we see that the lower quartile for 'days_listed' is 19.
days_listed_lower_quartile = data['days_listed'].quantile(0.25)

# View the result.
days_listed_lower_quartile

In [ ]:
# Create a slice with ads whose 'days_listed' value is less than the median. 
quickly_removed_ads = data.query('days_listed < @days_listed_lower_quartile')

In [ ]:
# Count how many "quickly removed ads" there are. 
quickly_removed_ads['days_listed'].count()

Just out of curiosity, check the characteristics of "quickly removed ads"?

In [ ]:
# Check the paint colour. 
#quickly_removed_ads['filled_paint_color'].value_counts()

In [ ]:
# Check the transmission type. 
#quickly_removed_ads['transmission'].value_counts()

In [ ]:
# Check the vehicle's age.
#quickly_removed_ads['age'].value_counts()

In [ ]:
# Check the mileage (although it will not be accurate since I did not categorize the values into ranges).
#quickly_removed_ads['mileage_median_combined'].value_counts()

In [ ]:
# Check the condition.
#quickly_removed_ads['condition'].value_counts()

[Conclusion] There are 12561 ads that can be defined as "quickly_removed_ads". This is indeed about 24% of the total ads placed (= 12561 / 51525).

**ads which were listed for an abnormally long time**

According to the descriptive statistics, the max is 271. But according to the boxplot, the max is about 100, and all the values above the max are displayed as outliers. 

Looking at the histogram, I would say 150 is the threshold, beyond which we can classify the ads as being listed for an abnormally long time. 

In [ ]:
# Set the threshold to 150.
abnormally_long_threshold = 150

In [ ]:
# Create a slice with ads whose 'days_listed' value is above the threshold. 
abnormally_persistent_ads = data.query('days_listed > @abnormally_long_threshold')

In [ ]:
# Count how many "abnormally_persistent_ads" there are. 
abnormally_persistent_ads['days_listed'].count()

[Conclusion] There are 243 ads that can be defined as being "listed for an abnormally long time". This is about 0.47% of the total ads placed (= 243 / 51525).

= Analyze the number of ads and the average price for each type of vehicle.
Plot a graph showing the dependence of the number of ads on the vehicle
type. Select the two types with the greatest number of ads. =

-* Analyze the number of ads and the average price for each type of vehicle. *-

In [ ]:
# Create a pivot table by grouping the data by vehicle type.
ads_by_vehicle_type_pivot = data.pivot_table(
    index = ['type'], values = ['date_posted', 'price'], aggfunc = ['count', 'mean']
)

# View the pivot table from the least number of ads to .
ads_by_vehicle_type_pivot

-* Plot a graph showing the dependence of the number of ads on the vehicle
type.  *-

In [ ]:
(data
     .pivot_table(index = ['type'], values = 'date_posted', aggfunc = 'count')
     .plot(grid=True, figsize=(12, 5), rot=90, style='o')
) 

[Comment] In my local environment (jupyter notebook), there is more space between the y-axis and "SUV" and looks better. The same goes for the right hand frame of the graph and "wagon".

-* Select the two types with the greatest number of ads.  *-

1. SUV
2. truck

= What factors impact the price most? Take each of the popular types you
detected at the previous stage and study whether the price depends on
age, mileage, condition, transmission type, and color. For categorical
variables (transmission type and color), plot box-and-whisker charts, and
create scatterplots for the rest. When analyzing categorical variables, note
that the categories must have at least 50 ads; otherwise, their parameters
won't be valid for analysis. =

Make a data slice for each type to make comparisons. 

In [ ]:
# Make a data slice of the 'data' dataframe for 'type' = SUV.
data_SUV = data.query('type == "SUV"')

# View the data slice.
#data_SUV

In [ ]:
# Make a data slice of the 'data' dataframe for 'type' = truck.
data_truck = data.query('type == "truck"')

# View the data slice.
#data_truck

-* Does the price depend on age? *-

In [ ]:
# Draw a scatterplot for SUV.
data_SUV.plot.scatter(x='age', y='price', alpha=0.03, grid=True);

In [ ]:
# Draw a scatterplot for trucks.
data_truck.plot.scatter(x='age', y='price', color='pink', alpha=0.03, grid=True);

[Observations] 

By and large, there is a negative correlation between price and age for both vehicle types - the younger a vehicle, the highter the price. 

In [ ]:
# Calculate the Pearson correlation coefficient between price and vehicle's age in each data slice. 
print('SUV:', data_SUV['age'].corr(data_SUV['price']))
print('Trucks:', data_truck['age'].corr(data_truck['price']))

[Observation] Assumption: 
The relationship between 'age' and 'price' is linear.

A rule of thumb for interpreting the strength of a relationship between two variables:
* r < 0.3: None or very weak
* 0.3 < r <0.5: Weak
* 0.5 < r < 0.7: Moderate
* r > 0.7: Strong

Their relationship is a negative correlation of a weak to moderate degree. 

-* Does the price depend on mileage? *-

In [ ]:
# Draw a scatterplot for SUV.
data_SUV.plot.scatter(x='mileage_median_combined', y='price', alpha=0.03, grid=True);

In [ ]:
# Draw a scatterplot for trucks.
data_truck.plot.scatter(x='mileage_median_combined', y='price', color='pink', alpha=0.03, grid=True);

[Observations] 

By and large, there is a negative correlation between price and mileage for both vehicle types - the lower the mileage, the highter the price. 

In [ ]:
# Calculate the Pearson correlation coefficient between price and mileage in each data slice. 
print('SUV:', data_SUV['mileage_median_combined'].corr(data_SUV['price']))
print('Trucks:', data_truck['mileage_median_combined'].corr(data_truck['price']))

[Observation] Assumption: 
The relationship between 'mileage' and 'price' is linear.

Their relationship is a negative correlation of a weak to moderate degree. 

-* Does the price depend on condition? *-

In [ ]:
# Draw a scatterplot for SUV.
data_SUV.plot.scatter(x='condition_num', y='price', alpha=0.03, grid=True);

In [ ]:
# Draw a scatterplot for trucks.
data_truck.plot.scatter(x='condition_num', y='price', color='pink', alpha=0.03, grid=True);

[Observations] 

* If there was a correlation, I would expect to see a triangle starting at 0 on the x-axis and steadily growing bigger towards the top right hand corner of the graph space above 5. But there is no such triangle here in either of the vehicle types. 
* The mid-range conditions tend to be more pricey than the others. 
* I think a condition scale only reflects a subjective opinion. The seller may be of opinion that the vehicle is in "excellent" condition, but another person (a potential buyer or a car dealer) may not agree. Also, choosing a condition scale is very arbitrary. In other words, the condition scale does not accurately reflect the value of a vehicle, so it is not a factor that affects the price. 
* Condition levels such as "new" and "like new" are less believable when it comes to used cars, so potential buyers will be less trusting of those ads. 

In [ ]:
# Calculate the Pearson correlation coefficient between price and condition in each data slice. 
print('SUV:', data_SUV['condition_num'].corr(data_SUV['price']))
print('Trucks:', data_truck['condition_num'].corr(data_truck['price']))

[Observation] Assumption: 
The relationship between 'condition' and 'price' is linear.

As expected, their relationship is a positive correlation of a very weak degree or practically non-existent. 

-* Does the price depend on transmission type? *-

Note: the categories must have at least 50 ads; otherwise, their parameters will not be valid for analysis.D

In [ ]:
# Draw a box-and-whisker chart with Seaborn for SUV.
sns.set_style("whitegrid")
plt.figure(figsize=(10,6))
SUV_bplot_trans_price = sns.boxplot(y='price', x='transmission', data=data_SUV, width=0.5, palette='Set3')
SUV_bplot_trans_price.axes.set_title("SUV: Correlation between Vehicle Price and Transmission Type", fontsize=12);
SUV_bplot_trans_price.set_xlabel("Transmission Type", fontsize=12);
SUV_bplot_trans_price.set_ylabel("Price", fontsize=12);
SUV_bplot_trans_price.tick_params(labelsize=12)

In [ ]:
# Draw a box-and-whisker chart with Seaborn for trucks.
#data_SUV.plot(kind='box');
sns.set_style("whitegrid")
plt.figure(figsize=(10,6))
truck_bplot_trans_price = sns.boxplot(y='price', x='transmission', data=data_truck, width=0.5, palette='Set1')
truck_bplot_trans_price.axes.set_title("Trucks: Correlation between Vehicle Price and Transmission Type", fontsize=12);
truck_bplot_trans_price.set_xlabel("Transmission Type", fontsize=12);
truck_bplot_trans_price.set_ylabel("Price", fontsize=12);
truck_bplot_trans_price.tick_params(labelsize=12)

[Observations] 

* In both vehicle types, 'automatic' vehicles tend to be priced higher than the max, followed by 'manual' ones. 
* For SUV, 'manual' vehicles tend to be more expensive than 'automatic' ones, whereas for trucks, it is the opposite. 
* The majority of vehicles with 'other' transmission types tend to be within the normal price range. 

[QUESTION] How do I make the plot area and the font of the categorical labels ("automatic", "manual", "other") bigger? I could not link plt.figure(figsize=(10, 6)) to the dataset 'truck_bplot_trans_price' for instance.

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
- If you put `plt.figure(figsize=(10,6))` to the first line of the code the plot area will be adjusted.

- To change the labels font size you can the following code line  `SUV_bplot_trans_price.tick_params(labelsize=12)`

</div>

<div class="alert alert-info"> <b>Student comments:</b> Got it!</div>  

[QUESTION] In my local jupyter notebook environment, the grid is automatically displayed in the boxplots. 
sns.set(style='whitegrid') or anything else does not work. Could you tell me the right code?

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>

Yandex jupyter notebook environment has most likely older seaborn version but if you put `sns.set_style("whitegrid")` to the first line of the code the plot style will be adjusted. 

</div>

<div class="alert alert-info"> <b>Student comments:</b> With the grid displayed, it's now much easier to know the values of the outliers. Thank you. </div>  

-* Does the price depend on color? Plot box-and-whisker charts.*-

Note: the categories must have at least 50 ads; otherwise, their parameters will not be valid for analysis.

In [ ]:
# Draw a box-and-whisker chart with Seaborn for SUV.
sns.set_style("whitegrid")
plt.figure(figsize=(10,6))
SUV_bplot_colour_price = sns.boxplot(y='price', x='filled_paint_color', data=data_SUV, width=0.5, palette='Set3')
SUV_bplot_colour_price.axes.set_title("SUV: Correlation between Vehicle Price and Paint Colour", fontsize=12);
SUV_bplot_colour_price.set_xticklabels(SUV_bplot_colour_price.get_xticklabels(),rotation=90);
SUV_bplot_colour_price.set_xlabel("Paint Colour", fontsize=12);
SUV_bplot_colour_price.set_ylabel("Price", fontsize=12);
SUV_bplot_trans_price.tick_params(labelsize=12)

In [ ]:
# Draw a box-and-whisker chart with Seaborn for trucks.
sns.set_style("whitegrid")
plt.figure(figsize=(10,6))
truck_bplot_colour_price = sns.boxplot(y='price', x='filled_paint_color', data=data_truck, width=0.5, palette='Set1')
truck_bplot_colour_price.axes.set_title("Trucks: Correlation between Vehicle Price and Paint Colour", fontsize=12);
truck_bplot_colour_price.set_xticklabels(truck_bplot_colour_price.get_xticklabels(),rotation=90);
truck_bplot_colour_price.set_xlabel("Paint Colour", fontsize=12);
truck_bplot_colour_price.set_ylabel("Price", fontsize=12);
SUV_bplot_trans_price.tick_params(labelsize=12)

[Observations] 

* For SUV, more vehicles tend to be priced higher than the normal range, compared to trucks in general, though there are many more outliers in the trucks data.
* For SUV, white seems to be the most popular colour and many more vehicles tend to be priced higher than the normal range, followed by red and black. For trucks, white, grey and black seem to be the easiest colours to sell, and buyers tend to put higher prices outside the normal range. 

[A side comment]
Statistically speaking, there are many records where the information on colour is missing ("unknown"), and it is a shame that they could not contribute to the statistics of understanding the correlation between colour and price better. 

Lastly, check using the whole dataset if there is a degree of correlation between the following variable pairs.

In [ ]:
# Is there a correlation between price and vehicle's age?
#print('Correlation between price and vehicle\'s age:', data['age'].corr(data['price']))

In [ ]:
# Is there a correlation between price and mileage?
#print('Correlation between price and mileage:', data['mileage_median_combined'].corr(data['price']))

In [ ]:
# Is there a correlation between 'price' and 'condition'?
#print('Correlation between price and condition:', data['condition_num'].corr(data['price']))

<div class="alert alert-block alert-success">
<b>Reviewer's comment v1:</b>
    
Excellent data analysis with correct conclusions and different graph types.

You covered all possilbe questions and dependencies between data. Also I really liked your observations and conclusions.

As an extra mile, it is also possible to create correlation matrix to check the correlation of different features.

</div>

<div class="alert alert-info"> <b>Student comments:</b> I have added a correlation matrix. </div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
Great!

</div>

In [ ]:
# Make a new dataframe containing only the relevant variables. 
final_df = data[['price', 'age', 'mileage_annual_average', 'condition_num']].copy()

In [ ]:
# Find the correlation coefficients for all the pairs of variables. 
print(final_df.corr())

In [ ]:
# Let's visualise the data on a scatterplot matrix. Highlight the graphs of our interest in pink for a clearer presentation. 
pd.plotting.scatter_matrix(final_df, figsize=(10, 6), color='pink');

[Observation] The above are the scatterplots drawn using the whole dataset (including only the relevant quantitative variables). They resemble those of the SUV and trucks data we studied ealier. This is an indication that the SUV and trucks were a good representation that reflected accurately the general characteristics of the whole dataset.

* price vs age: there is a negative correlation - the younger a vehicle, the highter the price.
* price vs mileage: there is a negative correlation - the lower the mileage, the highter the price.
* price vs condition: no correlation can be seen. 

We can also see that:
* age vs mileage: unexpectedly, there is a negative correlation - the younger a vehicle, the less mileage it has done. I would have expected a vehicle to accumulate mileage as it ages, but the graph indicates otherwise. 
<br>It is possible that: 
<br>o people's life style changed over the years that we travel a lot more and at speed, compared to the past, and/or
<br>o the younger a vehicle, the more powerful engine it is equipped with, making it capable of travelling more distance without breaking down. 
* condition vs mileage: no correlation can be seen.
* age vs condition: no correlation can be seen.

## Overall conclusion

[Executive summary]
So what factors impact the price the most? 

In short, the vehicle's age, mileage, transmission type and colour all contribute to the vehicle's price. Vehicles which are recent models, have done low mileage, equipped with an automatic gear, and white in colour can request a higher asking price outside the normal range, and are the easiest to sell. Condition levels should be appealing yet believable, so "excellent" and "good" seem to strike a balance. 

The Pearson's correlation coefficient may not back up my claims, but that is what I saw in the data I was given. 

Crankshaft List may leverage the data to provide sellers the following consultation services:
* suggest an asking price, based on the vehicle's model year, model, number of cylinders, transmission type and vehicle type to offer potential buyers an attractive and yet fair price
* let the seller in on the secret that s/he can ask for a higher asking price, if the vehicle has the winning combination of right age, mileage, transmission type and colour
* advise how to make a wise choice in the 'condition' scale, not so much as to gain the trust of potential buyers, but at least not to create a sense of distrust in potential buyers, by selecting one of the mid-range options


[Specifics - Data preprocessing]
* Missing values: no rows were deleted for missing a value. The following variables were missing values in some of the rows, and  were handled as below in order to restore them by imputation: 
<br>o 'cylinders': an educated guess was made by grouping the data by 'model_year' and 'model' then identifying the most common 'cylinders' value for that pair. Where there was more than one 'cylinders' value, the minimum was chosen. Where no 'cylinders' could be identified, the same process was repeated using 'model' only. The most common value was then used to fill the missing values. 
<br>o 'model_year': an educated guess was made by grouping the data by 'model' and 'mileage' then identifying the most common 'model_year' value for that pair. Where there was more than one 'model_year' value, the minimum was chosen. Where no 'model_year' could be identified, the same process was repeated using 'model' and 'cylinders', then further using 'model' and 'transmission'. The most common value was then used to fill the missing values.
<br>o 'mileage': an educated guess was made by grouping the data by 'model_year' and 'model' then calculating the median 'mileage'  value for that pair. Where no 'mileage' median could be obtained due to the absence of data, the same process was repeated using 'model' and 'cylinders'. The median was then used to fill the missing values.
<br>o 'paint_color': the missing values were filled with the term, 'unknown'. 
<br>o 'is_4wd': the missing values indicated that a vehicle was not a 4wd, and therefore, were filled with a zero. 

* Data type conversion: the data type was modified for ease of calculation and understanding for the following variables as below: 
<br>o 'model_year': modified from float to int
<br>o 'is_4wd': modified from float to boolean via int
<br>o 'cylinders': modified from float to int
<br>o 'date_posted': modified from string to date-time

* Variable renaming: one variable was renamed for ease of understanding as below:
<br>o 'odometer': the variable was renamed 'mileage'.

* Duplicates: no rows were removed for being duplicates of each other, but I would like to mention the following: 
<br>o No rows were "column for column" duplicates of each other, though there were rows which were thought to be the same ad being reactivated repeatedly period after period since they and were identical in nine columns.
<br>o There were inconsistencies in 'model' whereby the same 'model' value was found in two different forms, thereby, causing inaccuracy in aggregation. The issue was resolved by unifying all the variations into a single form. 

* Additional columns: as per instructed in the project description, the following variables were calculated and added to the dataset:
<br>o 'day_of_week', 'month', 'year': the information was extracted from 'date_posted'.
<br>o 'age': the vehicle's age was calculated from the post-imputation 'model_year' values and 'date_posted'. The illogical value of 'age' = 0 that arose during the calculation was corrected to 1. 
<br>o vehicle's annual average 'mileage': this was calculated from the post-imputation values of 'mileage' and 'age'.
<br>o 'condition' as quantitative values: the original string values were expressed in terms of a numerica scale between 0 and 5. 

[Specifics - Exploratory Data Analysis]
* 'price', 'age', 'mileage', 'cylinders' and 'condition':
<br>o Each variable was looked at using a histogram and a boxplot to study the effect of outliers that they obscure the majority of the data by clumping them together to one side, rendering the histogram unable to show their detail.
<br>o A new histogram was plotted out of filtered data without the outliers, and was compared to the previous histogram to understand the benefit of identifying the threshold and removing the outliers. 

* 'days_listed':
<br>o The variable was singled out and studied closely with the aid of a histogram, a boxplot and descriptive statistics. 
<br>o The mean and the median were used as the benchmark to describe the typical lifetime of an ad, and to identify those ads that were removed quickly and those that were listed for an abnormally long time. 

* Analysis - the factors that influece a vehicle's price
<br>o Two types of vehicles with the most number of ad placements were identified as the top two types in demand, which reflected the general characteristics of the whole dataset. 
<br>o The average price for each type was calculated.
<br>o Using the two vehicle types as data slices, any relationship that may exist between 'price' and each of 'age', 'mileage', 'condition', 'transmission type' and 'color' variables was examined. It was verified that there were at least 50 ad placements for each of the two selected vehicle types to confirm that the sample size was large enough to ensure the statistical validity of the data studied. 

<div class="alert alert-danger">
<b>Reviewer's comment v1:</b> 
    
Overall you did a great research. 

- Nevertheless, general conclusions represent the overall work progress that you achieved. On a real project, this is probably the only thing the business will read. Therefore, it is crucial to indicate in a structured way all conclusions that you made on each step in the project. 
    
For example:
1. Replaced missing values in the following data with the following method.
2. Replaced data types in the following columns.
3. etc.
4. etc.
    

- It is also important to provide explanations and interpretations that will be interesting for business based on your analysis.   

</div>

<div class="alert alert-info"> <b>Student comments:</b> I thought I should make the final conclusion as short and concise as possible for my "fictitious target audience" (company executives) by writing the answer to the question ("which factors affect the price of a vehicle?") only, and I really tried to make it short. 

I have expanded my conclusion now. :)
</div>  

<div class="alert alert-block alert-success">
<b>Reviewer's comment v2:</b>
    
It should be again somewhere in the middle (not too long, not too short). 

Now you made great overall conclusions and research! Your insights and recommendations are correct and could be helpful for business owners.

</div>

# Project completion checklist

Mark the completed tasks with 'x'. Then press Shift+Enter.

- [x]  file opened
- [x]  files explored (first rows printed, info() method)
- [x]  missing values determined
- [x]  missing values filled in
- [x]  clarification of the discovered missing values provided
- [x]  data types converted
- [x]  explanation of which columns had the data types changed and why
- [x]  calculated and added to the table: day of the week, month, and year the ad was placed
- [x]  calculated and added to the table: the vehicle's age (in years) when the ad was placed
- [x]  calculated and added to the table: the vehicle's average mileage per year
- [x]  the following parameters investigated: price, vehicle's age when the ad was placed, mileage, number of cylinders, and condition
- [x]  histograms for each parameter created
- [x]  task completed: "Determine the upper limits of outliers, remove the outliers and store them in a separate DataFrame, and continue your work with the filtered data."
- [x]  task completed: "Use the filtered data to plot new histograms. Compare them with the earlier histograms (the ones that included outliers). Draw conclusions for each histogram."
- [x]  task completed: "Study how many days advertisements were displayed (days_listed). Plot a histogram. Calculate the mean and median. Describe the typical lifetime of an ad. Determine when ads were removed quickly, and when they were listed for an abnormally long time.  "
- [x]  task completed: "Analyze the number of ads and the average price for each type of vehicle. Plot a graph showing the dependence of the number of ads on the vehicle type. Select the two types with the greatest number of ads. "
- [x]  task completed: "What factors impact the price most? Take each of the popular types you detected at the previous stage and study whether the price depends on age, mileage, condition, transmission type, and color. For categorical variables (transmission type and color), plot box-and-whisker charts, and create scatterplots for the rest. When analyzing categorical variables, note that the categories must have at least 50 ads; otherwise, their parameters won't be valid for analysis.  "
- [x]  each stage has a conclusion
- [x]  overall conclusion drawn